### ISSUE TITLE
Proposal for a new tutorial : calculating the noise power of a signal

### ISSUE THREAD

**Issue by waterwin** [dspsandbox/FPGA-Notes-for-Scientists#2]
After the tutorial for the use of DMA it would be very interesting to make use of that setup as follows:

1. Acquire a frequency slice of 1 MHz out of the full BW of the RP (0-54 MHz) 
2. Calculate the power in that signal slice via a FFT/DFT on the FPGA
3. Store the result in a PS accessible location with timestamp, border frequencies (low-high), FFT-bin width, integration length/signal length
4. Set-able parameters could be center frequency, BW of acquired signal, FFT-bin, acquisition length
5. Making the above automated to do this for the total RP BW in a period of x minutes doing all bins for y seconds.

I can of course answer questions or help to give a better description when needed

**Comment by dspsandbox** [comment]
Thanks for the feedback, 
a real-time spectral power meter is a cool application. I won't have time to implement that in the following weeks but I can give you some suggestions on how to do it:

- I believe that a FFT/DFT is not required, alternatively you can use a configurable band-pass filter and measure the power of your filtered data.
- A band pass filter can be easily implemented by concatenating an IIR high-pass and an IIR-low pass filter 
- To measure the power it is as simple as squaring your signal and sending the squared signal through a IIR-low pass filter

DATA IN -----> IIR band-pass -----> multiplier (x^2) ------> low-pass ------> DATA OUT
