### ISSUE TITLE
Constraint files

### ISSUE THREAD

**Issue by Gmotion94** [dspsandbox/FPGA-Notes-for-Scientists#6]
Hi, @dspsandbox Thanks for your work and for sharing your knowledge- I am also from a physics background this is very helpful for me. I would like to ask where can i download the Red-Pitaya 125-14 constraints file? as the provided link seems not to be working.

Thanks

**Comment by dspsandbox** [comment]
Hi @Gmotion94, I am glad to hear that the tutorial is useful to you. The constraints file is here; [FPGA-Notes-for-Scientists/sdc/redpitaya-125-14.xdc](https://github.com/dspsandbox/FPGA-Notes-for-Scientists/blob/main/sdc/redpitaya-125-14.xdc)
BR,
Pau

**Comment by Gmotion94** [comment]
@dspsandbox another issue I'm having is that the suggested prebuilt board agnostic is "PYNQ rootfs arm v2.6" however on the link: http://www.pynq.io/board.html/ the minimum is 2.7, not 2.6 any suggestions on that?

**Comment by Gmotion94** [comment]
Hi Paul 

May i please bother you again: so i have followed all the instructions on tutorial 1(LED_BLINK) on Vivado up-to generating the bitstream file (overlay) 

![Screenshot from 2022-12-07 16-51-45](https://user-images.githubusercontent.com/34322101/206217289-d567c846-4376-4b23-bac1-c3b3de6429b9.png)

However when i program the Red-Pitaya with the overlay image i'm getting an error.

![Screenshot from 2022-12-07 16-50-59](https://user-images.githubusercontent.com/34322101/206217722-44e70f14-12ba-483a-80f6-1567e7f0a901.png)
