### ISSUE TITLE
bitstream error 

### ISSUE THREAD

**Issue by Gmotion94** [dspsandbox/FPGA-Notes-for-Scientists#7]
Hi @dspsandbox 

May i please bother you again: so i have followed all the instructions on tutorial 1(LED_BLINK) on Vivado up-to generating the bitstream file (overlay) 

![Screenshot from 2022-12-07 19-15-19](https://user-images.githubusercontent.com/34322101/206246332-72e85885-e554-47ee-98cd-2f91c278fa4e.png)
![Screenshot from 2022-12-07 16-51-45](https://user-images.githubusercontent.com/34322101/206217289-d567c846-4376-4b23-bac1-c3b3de6429b9.png)
![Screenshot from 2022-12-07 17-21-40](https://user-images.githubusercontent.com/34322101/206219059-a664f4e8-20eb-4c49-a7ce-1e09cdc224aa.png)

However when i program the Red-Pitaya with the overlay image i'm getting this error - any advice on how to fix this?

![Screenshot from 2022-12-07 16-50-59](https://user-images.githubusercontent.com/34322101/206217722-44e70f14-12ba-483a-80f6-1567e7f0a901.png)

**Comment by dspsandbox** [comment]
Hi @Gmotion94 ,
base on the error message (in red) it seems that the overlay (or at least the LED_BLINK.bit file) is duplicated. Remove the one within /home/xilinx/jupyter_notebooks/ and try to run again your jupyter notebook.
Cheers!

**Comment by Gmotion94** [comment]
Hi Pau

even after removing the other LED_BLINK.bit file still getting the timeout error. However one point i will add though i used Vivado 2021.1 and Ubuntu 20.04 which i highly doubt would affect it.

![Screenshot from 2022-12-09 08-02-59](https://user-images.githubusercontent.com/34322101/206635560-6e0510d1-f63b-4eba-9141-b2b086ade99a.png)

**Comment by dspsandbox** [comment]
Can you try to reboot the board? I have seen in the past that some errors kill part of the PYNQ backend.

**Comment by dspsandbox** [comment]
Another point to check is that within Vivado you have selected the correct device. Are you using the Redpitaya-125-14 board file?

**Comment by Gmotion94** [comment]
Yep the target platform is Red-Pitaya 125-14

![Uploading Screenshot from 2022-12-09 10-17-22.png…]()

**Comment by Gmotion94** [comment]
Yep the target platform is RedPitaya-125-14

![Screenshot from 2022-12-09 10-17-22](https://user-images.githubusercontent.com/34322101/206657022-358bf3d8-6a6f-4e7e-9235-67ff7ed8e4ff.png)

**Comment by dspsandbox** [comment]
If rebooting doesn't help either I would try to blink the led through the already included base design. To this end just execute the code snipet shown here: https://github.com/dspsandbox/Pynq-Redpitaya-125/blob/master/README.md

If this works fine, the problem comes most probably from your generated overlay and the underlying Vivado project.

**Comment by Gmotion94** [comment]
I tried everything- changed the OS to Ubuntu 18.04.4 LTS as described here https://github.com/dspsandbox/FPGA-Notes-for-Scientists/wiki/Setting-up-your-system still nothing. 

![Screenshot from 2022-12-11 17-50-36](https://user-images.githubusercontent.com/34322101/206914424-f457f590-a91a-4a3f-94c2-4205291f4edd.png)

**Comment by dspsandbox** [comment]
Ok, this is very very strange... The base overlay should work for sure!  Can you maybe try to flash again your SD? Otherwise, is there anything special on your board? The board file only applies to the Redpitaya-125-14 with the Zynq 7010 chipset

**Comment by Gmotion94** [comment]
Ooh i see.. i just found out its a Redpitaya-125-14 with the Zynq 7020 chipset i will swap it tomorrow with 7010 at the office and see if i can get it running will update you.

**Comment by Gmotion94** [comment]
Finally it worked i changed to a 7010 chipset  :+1:  i could see LED flashing :')


![Screenshot from 2022-12-12 13-08-33](https://user-images.githubusercontent.com/34322101/207030715-d606af77-b8c9-4574-91b1-43547d896548.png)

**Comment by dspsandbox** [comment]
Great, I am glad to hear that! 
If at some point you are considering to go back to the Z7020, you can try to just change the part_name in [board.xml](https://github.com/dspsandbox/FPGA-Notes-for-Scientists/blob/main/board_files/redpitaya-125-14/1.0/board.xml) from xc7z010clg400-1 to xc7z020clg400-1. That should be enough to build your custom designs. The only thing I am not sure about is if the ADC and DAC IPs I created also apply to this board.

**Comment by Gmotion94** [comment]
Co-incidentally i read your blog: https://www.dspsandbox.org/ and your impressive CV to my surprise your career journey and research interests is exactly similar to my interests and goals. 

I recently completed a B.Sc. in Physics and Electronics at Rhodes University-South Africa and I'm currently working as a junior FPGA-DSP Engineer. I'm super fascinated by the RF/Microwave control of quantum processors and emulation of quantum algorithms on FPGAs I want to do this as an M.Sc. in Physics or Engineering with one of the universities here in my home country South Africa but there are no supervisors or experts within in this field :(

**Comment by dspsandbox** [comment]
Hi @Gmotion94, that 's a great coincidence! Let's further talk via PM (you have my e-mail and Linkedin in the CV).
BR,
Pau
